// Czech name day calendar data
const nameDays = {
    "1-1": ["Nový rok", "Miloslav"],
    "1-2": ["Karina", "Karína"],
    "1-3": ["Radmila", "Radmil"],
    "1-4": ["Diana", "Dian"],
    "1-5": ["Dalimil", "Dalimila"],
    "1-6": ["Tři králové", "Baltazar", "Kašpar", "Melichar"],
    "1-7": ["Vilma", "Vilém"],
    "1-8": ["Čestmír", "Čestmíra"],
    "1-9": ["Vladan", "Vladana"],
    "1-10": ["Břetislav", "Břetislava"],
    "1-11": ["Bohdana", "Bohdan"],
    "1-12": ["Pravoslav", "Pravoslava"],
    "1-13": ["Edita", "Edith"],
    "1-14": ["Radovan", "Radovana"],
    "1-15": ["Alice", "Alena"],
    "1-16": ["Ctirad", "Ctibor"],
    "1-17": ["Drahoslav", "Drahoslava"],
    "1-18": ["Vladislav", "Vladislava"],
    "1-19": ["Doubravka", "Doubrava"],
    "1-20": ["Ilona", "Ilja"],
    "1-21": ["Běla", "Bělka"],
    "1-22": ["Slavomír", "Slavomíra"],
    "1-23": ["Zdeněk", "Zdenka"],
    "1-24": ["Milena", "Milana"],
    "1-25": ["Miloš", "Miloslav"],
    "1-26": ["Zora", "Zoran"],
    "1-27": ["Ingrid", "Ingrida"],
    "1-28": ["Otýlie", "Otýlka"],
    "1-29": ["Zdislava", "Zdislav"],
    "1-30": ["Robin", "Robina"],
    "1-31": ["Marika", "Marika"],
    
    "2-1": ["Hynek", "Hynka"],
    "2-2": ["Nela", "Nelly"],
    "2-3": ["Blažej", "Blažena"],
    "2-4": ["Jarmila", "Jarmil"],
    "2-5": ["Dobromila", "Dobromil"],
    "2-6": ["Vanda", "Vanda"],
    "2-7": ["Veronika", "Veronika"],
    "2-8": ["Milada", "Miladka"],
    "2-9": ["Apolena", "Apolena"],
    "2-10": ["Mojmír", "Mojmíra"],
    "2-11": ["Božena", "Boženka"],
    "2-12": ["Slavěna", "Slavěna"],
    "2-13": ["Věnceslav", "Věnceslava"],
    "2-14": ["Valentýn", "Valentýna"],
    "2-15": ["Jiřina", "Jiřinka"],
    "2-16": ["Ljuba", "Ljubka"],
    "2-17": ["Miloslava", "Miloslav"],
    "2-18": ["Gizela", "Gizelka"],
    "2-19": ["Patrik", "Patrika"],
    "2-20": ["Oldřich", "Oldřiška"],
    "2-21": ["Lenka", "Lenka"],
    "2-22": ["Petr", "Petra"],
    "2-23": ["Svatopluk", "Svatopluka"],
    "2-24": ["Matěj", "Matějka"],
    "2-25": ["Liliana", "Liliana"],
    "2-26": ["Dorota", "Dorotka"],
    "2-27": ["Alexandr", "Alexandra"],
    "2-28": ["Lumír", "Lumíra"],
    "2-29": ["Horymír", "Horymíra"],
    
    "3-1": ["Bedřich", "Bedřiška"],
    "3-2": ["Anežka", "Anežka"],
    "3-3": ["Kamil", "Kamila"],
    "3-4": ["Stela", "Stelka"],
    "3-5": ["Kazimir", "Kazimíra"],
    "3-6": ["Miroslav", "Miroslava"],
    "3-7": ["Tomáš", "Tomáška"],
    "3-8": ["Gabriela", "Gabriela"],
    "3-9": ["Františka", "Františka"],
    "3-10": ["Viktorie", "Viktorka"],
    "3-11": ["Anděla", "Andělka"],
    "3-12": ["Řehoř", "Řehořka"],
    "3-13": ["Růžena", "Růženka"],
    "3-14": ["Rút", "Rútka"],
    "3-15": ["Ida", "Idka"],
    "3-16": ["Elena", "Elenka"],
    "3-17": ["Vlastimil", "Vlastimila"],
    "3-18": ["Eduard", "Eduarda"],
    "3-19": ["Josef", "Josefa"],
    "3-20": ["Světlana", "Světlanka"],
    "3-21": ["Radek", "Radka"],
    "3-22": ["Leona", "Leonka"],
    "3-23": ["Ivona", "Ivona"],
    "3-24": ["Gabriel", "Gabriela"],
    "3-25": ["Marián", "Mariána"],
    "3-26": ["Emanuel", "Emanuela"],
    "3-27": ["Dita", "Ditka"],
    "3-28": ["Soňa", "Soňka"],
    "3-29": ["Taťána", "Taťánka"],
    "3-30": ["Arnošt", "Arnoštka"],
    "3-31": ["Kvido", "Kvida"],
    
    "4-1": ["Hugo", "Hugona"],
    "4-2": ["Erika", "Erika"],
    "4-3": ["Richard", "Richarda"],
    "4-4": ["Ivana", "Ivanka"],
    "4-5": ["Miroslava", "Miroslav"],
    "4-6": ["Vendula", "Vendulka"],
    "4-7": ["Heřman", "Heřmana"],
    "4-8": ["Ema", "Emka"],
    "4-9": ["Dušan", "Dušana"],
    "4-10": ["Darja", "Darjka"],
    "4-11": ["Izabela", "Izabelka"],
    "4-12": ["Julius", "Juliána"],
    "4-13": ["Aleš", "Aleška"],
    "4-14": ["Vincenc", "Vincencie"],
    "4-15": ["Anastázie", "Anastázie"],
    "4-16": ["Irena", "Irenka"],
    "4-17": ["Rudolf", "Rudolfa"],
    "4-18": ["Valérie", "Valerka"],
    "4-19": ["Rostislav", "Rostislava"],
    "4-20": ["Marcela", "Marcela"],
    "4-21": ["Alexandra", "Alexandr"],
    "4-22": ["Evženie", "Evženka"],
    "4-23": ["Vojtěch", "Vojtěška"],
    "4-24": ["Jiří", "Jiřina"],
    "4-25": ["Marek", "Marka"],
    "4-26": ["Oto", "Otka"],
    "4-27": ["Jaroslav", "Jaroslava"],
    "4-28": ["Vlastislav", "Vlastislava"],
    "4-29": ["Robert", "Roberta"],
    "4-30": ["Blahoslav", "Blahoslava"],
    
    "5-1": ["Svátek práce", "Květoslav"],
    "5-2": ["Zikmund", "Zikmunda"],
    "5-3": ["Alexej", "Alexeja"],
    "5-4": ["Květoslav", "Květoslava"],
    "5-5": ["Klaudie", "Klaudie"],
    "5-6": ["Radoslav", "Radoslava"],
    "5-7": ["Stanislav", "Stanislava"],
    "5-8": ["Den vítězství", "Miloslav"],
    "5-9": ["Ctibor", "Ctibora"],
    "5-10": ["Blažena", "Blaženka"],
    "5-11": ["Svatava", "Svatavka"],
    "5-12": ["Pankrác", "Pankrácie"],
    "5-13": ["Servác", "Servácie"],
    "5-14": ["Bonifác", "Bonifácie"],
    "5-15": ["Žofie", "Žofka"],
    "5-16": ["Přemysl", "Přemysla"],
    "5-17": ["Aneta", "Anetka"],
    "5-18": ["Nataša", "Nataška"],
    "5-19": ["Ivo", "Iva"],
    "5-20": ["Zbyšek", "Zbyška"],
    "5-21": ["Monika", "Monika"],
    "5-22": ["Emil", "Emila"],
    "5-23": ["Vladimír", "Vladimíra"],
    "5-24": ["Jana", "Janka"],
    "5-25": ["Viola", "Violka"],
    "5-26": ["Filip", "Filipa"],
    "5-27": ["Valdemar", "Valdemara"],
    "5-28": ["Vilém", "Viléma"],
    "5-29": ["Maxmilián", "Maxmiliána"],
    "5-30": ["Ferdinand", "Ferdinanda"],
    "5-31": ["Kamila", "Kamilka"],
    
    "6-1": ["Laura", "Laurka"],
    "6-2": ["Jarmil", "Jarmila"],
    "6-3": ["Tamara", "Tamarka"],
    "6-4": ["Dalibor", "Dalibora"],
    "6-5": ["Dobroslav", "Dobroslava"],
    "6-6": ["Norbert", "Norberta"],
    "6-7": ["Iveta", "Ivetka"],
    "6-8": ["Medard", "Medarda"],
    "6-9": ["Stanislava", "Stanislav"],
    "6-10": ["Gita", "Gitka"],
    "6-11": ["Bruno", "Bruna"],
    "6-12": ["Antonie", "Antonka"],
    "6-13": ["Antonín", "Antonína"],
    "6-14": ["Roland", "Rolanda"],
    "6-15": ["Vít", "Víta"],
    "6-16": ["Zbyněk", "Zbynka"],
    "6-17": ["Adolf", "Adolfa"],
    "6-18": ["Milan", "Milana"],
    "6-19": ["Leoš", "Leoška"],
    "6-20": ["Květa", "Květka"],
    "6-21": ["Alois", "Aloise"],
    "6-22": ["Pavla", "Pavlínka"],
    "6-23": ["Zdeňka", "Zdeňka"],
    "6-24": ["Jan", "Jana"],
    "6-25": ["Ivan", "Ivana"],
    "6-26": ["Adriana", "Adrianka"],
    "6-27": ["Ladislav", "Ladislava"],
    "6-28": ["Lubomír", "Lubomíra"],
    "6-29": ["Petr", "Petra"],
    "6-30": ["Šárka", "Šárka"],
    
    "7-1": ["Jaroslava", "Jaroslav"],
    "7-2": ["Patricie", "Patricka"],
    "7-3": ["Radomír", "Radomíra"],
    "7-4": ["Prokop", "Prokopa"],
    "7-5": ["Cyril", "Cyrila"],
    "7-6": ["Mistr Jan Hus", "Jan"],
    "7-7": ["Bohuslava", "Bohuslav"],
    "7-8": ["Nora", "Norka"],
    "7-9": ["Drahoslava", "Drahoslav"],
    "7-10": ["Libuše", "Libuška"],
    "7-11": ["Olga", "Olga"],
    "7-12": ["Bořek", "Bořka"],
    "7-13": ["Markéta", "Markétka"],
    "7-14": ["Karolína", "Karolínka"],
    "7-15": ["Jindřich", "Jindřiška"],
    "7-16": ["Luboš", "Luboška"],
    "7-17": ["Martina", "Martinka"],
    "7-18": ["Drahomíra", "Drahomír"],
    "7-19": ["Čeněk", "Čeňka"],
    "7-20": ["Ilja", "Ilja"],
    "7-21": ["Vítězslav", "Vítězslava"],
    "7-22": ["Magdaléna", "Magdalénka"],
    "7-23": ["Libor", "Libora"],
    "7-24": ["Kristýna", "Kristýnka"],
    "7-25": ["Jakub", "Jakuba"],
    "7-26": ["Anna", "Anička"],
    "7-27": ["Věroslav", "Věroslava"],
    "7-28": ["Viktor", "Viktora"],
    "7-29": ["Marta", "Martka"],
    "7-30": ["Bořivoj", "Bořivoja"],
    "7-31": ["Ignác", "Ignácie"],
    
    "8-1": ["Oskar", "Oskara"],
    "8-2": ["Gustav", "Gustava"],
    "8-3": ["Miluše", "Miluška"],
    "8-4": ["Dominik", "Dominika"],
    "8-5": ["Kristián", "Kristiána"],
    "8-6": ["Oldřiška", "Oldřich"],
    "8-7": ["Lada", "Ladka"],
    "8-8": ["Soběslav", "Soběslava"],
    "8-9": ["Roman", "Romana"],
    "8-10": ["Vavřinec", "Vavřince"],
    "8-11": ["Zuzana", "Zuzanka"],
    "8-12": ["Klára", "Klárka"],
    "8-13": ["Alena", "Alenka"],
    "8-14": ["Alan", "Alana"],
    "8-15": ["Hana", "Hanka"],
    "8-16": ["Jáchym", "Jáchyma"],
    "8-17": ["Petra", "Petr"],
    "8-18": ["Helena", "Helenka"],
    "8-19": ["Ludvík", "Ludvíka"],
    "8-20": ["Bernard", "Bernarda"],
    "8-21": ["Johana", "Johanka"],
    "8-22": ["Bohuslav", "Bohuslava"],
    "8-23": ["Sandra", "Sandrika"],
    "8-24": ["Bartoloměj", "Bartoloměje"],
    "8-25": ["Radim", "Radima"],
    "8-26": ["Luděk", "Luděk"],
    "8-27": ["Otakar", "Otakara"],
    "8-28": ["Augustýn", "Augustýna"],
    "8-29": ["Evelína", "Evelínka"],
    "8-30": ["Vladěna", "Vladěnka"],
    "8-31": ["Pavlína", "Pavlína"],
    
    "9-1": ["Linda", "Linda"],
    "9-2": ["Adéla", "Adélka"],
    "9-3": ["Bronislav", "Bronislava"],
    "9-4": ["Jindřiška", "Jindřich"],
    "9-5": ["Boris", "Bora"],
    "9-6": ["Boleslav", "Boleslava"],
    "9-7": ["Regína", "Regínka"],
    "9-8": ["Mariana", "Marianka"],
    "9-9": ["Daniela", "Danielka"],
    "9-10": ["Irma", "Irmka"],
    "9-11": ["Denisa", "Deniska"],
    "9-12": ["Marie", "Marijka"],
    "9-13": ["Lubor", "Lubora"],
    "9-14": ["Radka", "Radek"],
    "9-15": ["Jolana", "Jolanka"],
    "9-16": ["Ludmila", "Ludmilka"],
    "9-17": ["Naděžda", "Nadějka"],
    "9-18": ["Kryštof", "Kryštofa"],
    "9-19": ["Zita", "Zitka"],
    "9-20": ["Oleg", "Olega"],
    "9-21": ["Matouš", "Matouška"],
    "9-22": ["Darina", "Darinka"],
    "9-23": ["Berta", "Bertka"],
    "9-24": ["Jaromír", "Jaromíra"],
    "9-25": ["Zlata", "Zlatka"],
    "9-26": ["Andrea", "Andrejka"],
    "9-27": ["Jonáš", "Jonáše"],
    "9-28": ["Václav", "Václava"],
    "9-29": ["Michal", "Michala"],
    "9-30": ["Jeroným", "Jeronýma"],
    
    "10-1": ["Igor", "Igora"],
    "10-2": ["Olívie", "Olívka"],
    "10-3": ["Bohumil", "Bohumila"],
    "10-4": ["František", "Františka"],
    "10-5": ["Eliška", "Eliška"],
    "10-6": ["Hanuš", "Hanuše"],
    "10-7": ["Justýna", "Justýnka"],
    "10-8": ["Věra", "Věrka"],
    "10-9": ["Štefan", "Štefana"],
    "10-10": ["Marina", "Marinka"],
    "10-11": ["Andrej", "Andrejka"],
    "10-12": ["Marcel", "Marcela"],
    "10-13": ["Renáta", "Renátka"],
    "10-14": ["Agáta", "Agátka"],
    "10-15": ["Tereza", "Terezka"],
    "10-16": ["Havel", "Havla"],
    "10-17": ["Hedvika", "Hedvička"],
    "10-18": ["Lukáš", "Lukáška"],
    "10-19": ["Michaela", "Michalka"],
    "10-20": ["Vendelín", "Vendelína"],
    "10-21": ["Brigita", "Brigitka"],
    "10-22": ["Sabina", "Sabinka"],
    "10-23": ["Teodor", "Teodora"],
    "10-24": ["Nina", "Ninka"],
    "10-25": ["Beáta", "Beátka"],
    "10-26": ["Erik", "Erika"],
    "10-27": ["Šarlota", "Šarlotka"],
    "10-28": ["Den vzniku samostatného československého státu", "Samostatnost"],
    "10-29": ["Silvie", "Silvinka"],
    "10-30": ["Tadeáš", "Tadeáše"],
    "10-31": ["Štěpánka", "Štěpán"],
    
    "11-1": ["Felix", "Felixa"],
    "11-2": ["Památka zesnulých", "Vzpomínka"],
    "11-3": ["Hubert", "Huberta"],
    "11-4": ["Karel", "Karl"],
    "11-5": ["Miriam", "Miriamka"],
    "11-6": ["Liběna", "Liběnka"],
    "11-7": ["Saskie", "Saskie"],
    "11-8": ["Bohumír", "Bohumíra"],
    "11-9": ["Bohdan", "Bohdana"],
    "11-10": ["Evžen", "Evžena"],
    "11-11": ["Martin", "Martina"],
    "11-12": ["Benedikt", "Benedikta"],
    "11-13": ["Tibor", "Tibora"],
    "11-14": ["Sáva", "Sávka"],
    "11-15": ["Leopold", "Leopolda"],
    "11-16": ["Otmar", "Otma"],
    "11-17": ["Mahulena", "Mahulenka"],
    "11-18": ["Romana", "Romanka"],
    "11-19": ["Alžběta", "Alžbětka"],
    "11-20": ["Nikola", "Nikolka"],
    "11-21": ["Albert", "Alberta"],
    "11-22": ["Cecílie", "Cecílka"],
    "11-23": ["Klement", "Klementa"],
    "11-24": ["Emílie", "Emilka"],
    "11-25": ["Kateřina", "Kačenka"],
    "11-26": ["Artur", "Artura"],
    "11-27": ["Xenie", "Xenka"],
    "11-28": ["René", "René"],
    "11-29": ["Zina", "Zinka"],
    "11-30": ["Ondřej", "Ondřejka"],
    
    "12-1": ["Iva", "Ivka"],
    "12-2": ["Blanka", "Blančička"],
    "12-3": ["Svatoslav", "Svatoslava"],
    "12-4": ["Barbora", "Barča"],
    "12-5": ["Jitka", "Jitka"],
    "12-6": ["Mikuláš", "Mikuláška"],
    "12-7": ["Ambrož", "Ambrožka"],
    "12-8": ["Květoslava", "Květoslav"],
    "12-9": ["Vratislav", "Vratislava"],
    "12-10": ["Julie", "Julinka"],
    "12-11": ["Dana", "Danka"],
    "12-12": ["Simona", "Simonka"],
    "12-13": ["Lucie", "Lucinka"],
    "12-14": ["Lýdie", "Lýdka"],
    "12-15": ["Radana", "Radanka"],
    "12-16": ["Albína", "Albínka"],
    "12-17": ["Daniel", "Daniela"],
    "12-18": ["Miloslav", "Miloslava"],
    "12-19": ["Ester", "Esterka"],
    "12-20": ["Dagmar", "Dagmara"],
    "12-21": ["Natálie", "Natálka"],
    "12-22": ["Šimon", "Šimonka"],
    "12-23": ["Vlasta", "Vlastka"],
    "12-24": ["Adam", "Adama"],
    "12-25": ["Boží hod vánoční", "Vánoce"],
    "12-26": ["Štěpán", "Štěpánka"],
    "12-27": ["Žaneta", "Žanetka"],
    "12-28": ["Bohumila", "Bohumil"],
    "12-29": ["Judita", "Juditka"],
    "12-30": ["David", "Davida"],
    "12-31": ["Silvestr", "Silvestra"]
};

// Initialize Telegram Web App
let tg = window.Telegram.WebApp;
tg.ready();
tg.expand();

// Format date for display
function formatDate(date) {
    const options = { 
        weekday: 'long', 
        year: 'numeric', 
        month: 'long', 
        day: 'numeric' 
    };
    return date.toLocaleDateString('cs-CZ', options);
}

// Get name day for a specific date
function getNameDay(date) {
    const month = date.getMonth() + 1;
    const day = date.getDate();
    const key = `${month}-${day}`;
    return nameDays[key] || ["Neznámé jméno"];
}

// Update the display
function updateDisplay() {
    const today = new Date();
    const tomorrow = new Date(today);
    tomorrow.setDate(tomorrow.getDate() + 1);
    
    // Get today's names
    const todayNames = getNameDay(today);
    const tomorrowNames = getNameDay(tomorrow);
    
    // Update today's display
    document.getElementById('today-date').textContent = formatDate(today);
    document.getElementById('today-names').textContent = todayNames.join(', ');
    
    // Update tomorrow's display
    document.getElementById('tomorrow-date').textContent = formatDate(tomorrow);
    document.getElementById('tomorrow-names').textContent = tomorrowNames.join(', ');
    
    // Hide loading and show content
    document.getElementById('loading').style.display = 'none';
    document.getElementById('content').style.display = 'block';
}

// Initialize the app
document.addEventListener('DOMContentLoaded', function() {
    updateDisplay();
});
